[project]
name = "t2"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "bs4>=0.0.2",
    "dotenv>=0.9.9",
    "requests>=2.32.5",
    "unsloth>=2025.9.9",
    "gguf>=0.10.0",
    "protobuf>=5.29.3",
    "pip>=25.2",
]
